### ISSUE TITLE
Firefox theme broke again, probably because of a Firefox update

### ISSUE THREAD

**Issue by AzhamProdLive** [gh0stzk/dotfiles#195]
[Basically the title]

The icons to close, reduce and maximize window are back for me : 
![image](https://github.com/gh0stzk/dotfiles/assets/73955243/018d136d-42e7-419f-a14f-aa946245a590)

Might just be a bug on my end, but I restarted firefox and it's still here 

My version : 
![image](https://github.com/gh0stzk/dotfiles/assets/73955243/b350dd9e-6ae6-47ed-a0e6-99187f7fde37)

**Comment by gh0stzk** [comment]
I searched your repo and couldn't find the firefox configuration, in the last commit I pushed the fix.
Add to userchrome.css:

```css
.titlebar-buttonbox-container {
  display: none;
}

.titlebar-spacer[type="post-tabs"] {
  display: none;
}
```
